site_name: dsgvo-kommentar.org

theme:
  
  name: material
  
  language: de
  
  palette:
  
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Zum dunklen Modus wechseln
  
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Zum hellen Modus wechseln
  
  font: false
  
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

repo_url: https://github.com/dsgvo-kommentar/mkdocs-page

nav:

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DSGVO_Kommentar
  copyright: Lizenziert unter der GNU GPLv3